version: '3'
services:
  gin:
    depends_on:
      - mariadb
    build: ./gin
    container_name: gin
    restart: always
    ports: 
      - "80:8080"
    stdin_open: true
    tty: true

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root00 # 注意
